name: ultrack-atini
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab
  - jupytext
  - jupyterlab-myst
  - jupyter-book
  - notebook
  - postgresql
  - cellpose<3
  - coin-or-cbc
  - gurobi
  - jupyter
  - nodejs
  - pip
  - higra
  - numpy<2
  - pip:
    - torch
    - py-ctcmetrics
    - napari[all]
    - ultrack
    - napari-plot-profile
